export const LOAD_FLIGHTS_SUCCESS = 'LOAD_FLIGHTS_SUCCESS';
export const LOAD_PASSENGERS_SUCCESS = 'LOAD_PASSENGERS_SUCCESS';
export const LOAD_LOGIN_SUCCESS = 'LOAD_LOGIN_SUCCESS';
export const UPDATE_LOGIN_SUCCESS = 'UPDATE_LOGIN_SUCCESS';
export const UPDATE_PASSENGER_SUCCESS = 'UPDATE_PASSENGER_SUCCESS';
export const CREATE_PASSENGER_SUCCESS = 'CREATE_PASSENGER_SUCCESS';
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
